name: live_chat_plus
description: "A Flutter plugin to bring LiveChat functionality to Flutter. It wraps chat-window android and ios SDKs, in addition to support for web"
version: 1.0.5
repository: https://github.com/deriv-com/live-chat
issue_tracker: https://github.com/deriv-com/live-chat/issues
homepage: https://github.com/deriv-com/live-chat

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.7.1
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/live_chat.js

  plugin:
    platforms:
      android:
        package: com.deriv.livechat.live_chat
        pluginClass: LiveChatPlugin
      ios:
        pluginClass: LiveChatPlugin
      web:
        pluginClass: LiveChatWeb
        fileName: _internal/live_chat_web.dart

